name: 'Validate Regression Test Output'
description: 'Validates the output of regression tests and determines if a test action should fail.'
inputs:
    ALLOWED_DURATION_DEVIATION:
        description: Allowable deviation in milliseconds for the mean duration in regression test results.
        required: true
    ALLOWED_RELATIVE_DURATION_DEVIATION:
        description: Allowable percentage deviation for the mean duration in regression test results.
        required: true
runs:
    using: 'node20'
    main: './index.js'
